apiVersion: v1
kind: Service
metadata:
  labels:
    app: rook-cassandra-np
  name: rook-cassandra-np
  namespace: rook-cassandra
spec:
  type: NodePort
  ports:
  - port: 9042
    nodePort: 30042
  selector:
    app: rook-cassandra